### ISSUE TITLE
Improve error handling in case where arc-data is loaded with @tables entries in .arc

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-data#9]
See: https://github.com/arc-repos/arc-data/blob/master/src/_init.js#L19-L20

**Comment by schpet** [comment]
probably related - when i try running `npx repl` in a freshly made arc project, i get an error here:

```
testapp $ npx repl
        app ⌁ testapp
     region ⌁ us-west-1
    profile ⌁ personal
    version ⌁ 5.5.0

#!/data> /private/tmp/testapp/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'slice' of undefined
    at _init (/private/tmp/testapp/node_modules/@architect/data/src/_init.js:20:27)
    at Object.<anonymous> (/private/tmp/testapp/node_modules/@architect/data/index.js:34:18)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _start (/private/tmp/testapp/node_modules/@architect/architect/src/repl/cli.js:27:31)
```

adding `@tables` to my .arc fixes it

**Comment by ryanblock** [comment]
Yeah, I think this is the same issue!

**Comment by brianleroux** [comment]
patched; this is no longer an error condition
